DROP TABLE IF EXISTS CENTROFORENSE;
DROP TABLE IF EXISTS INFORMEFORENSE;
DROP TABLE IF EXISTS MUESTRAFORENSE;

CREATE TABLE CENTROS_FORENSES (
    ID              INTEGER,
    NOMBRE          VARCHAR(150),
    PAIS            VARCHAR(100),
    NIVEL_SEGURIDAD INTEGER,
    AUTOR_EXAMEN    VARCHAR(150) NOT NULL,
    CONSTRAINT PK_CENTROS_FORENSES         PRIMARY KEY (ID),
    CONSTRAINT CK_CENTROS_NIVEL_SEGURIDAD  CHECK (NIVEL_SEGURIDAD >= 0),
    CONSTRAINT NN_CENTROS_NOMBRE           CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT NN_CENTROS_PAIS             CHECK (PAIS IS NOT NULL)
);

CREATE TABLE MUESTRAS_FORENSES (
    ID               INTEGER,
    CODIGO_CASO      VARCHAR(100),
    TIPO_MUESTRA     VARCHAR(100),
    FECHA_RECOGIDA   DATE,
    ESTADO_CUSTODIA  VARCHAR(100),
    FK_CENTRO_ID     INTEGER,
    AUTOR_EXAMEN     VARCHAR(150) NOT NULL,
    CONSTRAINT PK_MUESTRAS_FORENSES          PRIMARY KEY (ID),
    CONSTRAINT FK_MUESTRAS_CENTRO            FOREIGN KEY (FK_CENTRO_ID) REFERENCES CENTROS_FORENSES(ID),
    CONSTRAINT NN_MUESTRAS_CODIGO_CASO       CHECK (CODIGO_CASO IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_TIPO_MUESTRA      CHECK (TIPO_MUESTRA IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_FECHA_RECOGIDA    CHECK (FECHA_RECOGIDA IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_ESTADO_CUSTODIA   CHECK (ESTADO_CUSTODIA IS NOT NULL)
);

CREATE TABLE INFORMES_FORENSES (
    ID             INTEGER,
    ADN_POSITIVO   BOOLEAN,
    NIVEL_RIESGO   INTEGER,
    CONCLUSION     VARCHAR(500),
    FK_MUESTRA_ID  INTEGER,
    AUTOR_EXAMEN   VARCHAR(150) NOT NULL,
    CONSTRAINT PK_INFORMES_FORENSES       PRIMARY KEY (ID),
    CONSTRAINT FK_INFORMES_MUESTRA        FOREIGN KEY (FK_MUESTRA_ID) REFERENCES MUESTRAS_FORENSES(ID),
    CONSTRAINT UQ_INFORMES_MUESTRA        UNIQUE (FK_MUESTRA_ID),
    CONSTRAINT CK_INFORMES_NIVEL_RIESGO   CHECK (NIVEL_RIESGO >= 0 AND NIVEL_RIESGO <= 100),
    CONSTRAINT NN_INFORMES_CONCLUSION     CHECK (CONCLUSION IS NOT NULL),
    CONSTRAINT NN_INFORMES_ADN_POSITIVO   CHECK (ADN_POSITIVO IS NOT NULL)
);
