-- FIND ALL CENTROS FORENSES
SELECT ID, NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN
FROM CENTROS_FORENSES;

-- FIND CENTRO FORENSE BY ID
SELECT ID, NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN
FROM CENTROS_FORENSES
WHERE ID = ?;

-- FIND ALL MUESTRAS FORENSES
SELECT ID, CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, FK_CENTRO_ID, AUTOR_EXAMEN
FROM MUESTRAS_FORENSES;

-- FIND MUESTRA FORENSE BY ID
SELECT ID, CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, FK_CENTRO_ID, AUTOR_EXAMEN
FROM MUESTRAS_FORENSES
WHERE ID = ?;