-- FIND ALL CENTROS FORENSES
SELECT ID, NOMBRE, PAIS, NIVEL_SEGURIDAD, Moya_Diego
FROM CENTROS_FORENSES;

-- FIND CENTRO FORENSE BY ID
SELECT ID, NOMBRE, PAIS, NIVEL_SEGURIDAD, Moya_Diego
FROM CENTROS_FORENSES
WHERE ID = ?;

-- FIND ALL MUESTRAS FORENSES
SELECT ID, CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, FK_CENTRO_ID, Moya_Diego
FROM MUESTRAS_FORENSES;

-- FIND MUESTRA FORENSE BY ID
SELECT ID, CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, FK_CENTRO_ID, Moya_Diego
FROM MUESTRAS_FORENSES
WHERE ID = ?;


-- FIND ALL CENTROS FORENSES
SELECT ID, NOMBRE, PAIS, NIVEL_SEGURIDAD, Moya_Diego
FROM CENTROS_FORENSES;

-- FIND CENTRO FORENSE BY ID
SELECT ID, NOMBRE, PAIS, NIVEL_SEGURIDAD, Moya_Diego
FROM CENTROS_FORENSES
WHERE ID = ?;

-- FIND ALL MUESTRAS FORENSES
SELECT ID, CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, FK_CENTRO_ID, Moya_Diego
FROM MUESTRAS_FORENSES;

-- FIND MUESTRA FORENSE BY ID
SELECT ID, CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, FK_CENTRO_ID, Moya_Diego
FROM MUESTRAS_FORENSES
WHERE ID = ?;

-- FIND MUESTRAS BY CENTRO (TEST 5)
SELECT MF.ID, MF.CODIGO_CASO, MF.TIPO_MUESTRA, MF.FECHA_RECOGIDA, MF.ESTADO_CUSTODIA,
       CF.ID AS CENTRO_ID, CF.NOMBRE AS CENTRO_NOMBRE, CF.PAIS, CF.NIVEL_SEGURIDAD
FROM MUESTRAS_FORENSES MF
INNER JOIN CENTROS_FORENSES CF ON MF.FK_CENTRO_ID = CF.ID
WHERE CF.ID = ?;

-- FIND MUESTRA WITH INFORME (TEST 6 — relación 1:1)
SELECT MF.ID, MF.CODIGO_CASO, MF.TIPO_MUESTRA, MF.FECHA_RECOGIDA, MF.ESTADO_CUSTODIA,
       CF.ID AS CENTRO_ID, CF.NOMBRE AS CENTRO_NOMBRE, CF.PAIS, CF.NIVEL_SEGURIDAD,
       INF.ID AS INFORME_ID, INF.ADN_POSITIVO, INF.NIVEL_RIESGO, INF.CONCLUSION
FROM MUESTRAS_FORENSES MF
INNER JOIN CENTROS_FORENSES CF  ON MF.FK_CENTRO_ID  = CF.ID
INNER JOIN INFORMES_FORENSES INF ON INF.FK_MUESTRA_ID = MF.ID
WHERE MF.ID = ?;

-- FIND ALL INFORMES FORENSES
SELECT ID, ADN_POSITIVO, NIVEL_RIESGO, CONCLUSION, FK_MUESTRA_ID, Moya_Diego
FROM INFORMES_FORENSES;

-- FIND INFORME BY ID
SELECT ID, ADN_POSITIVO, NIVEL_RIESGO, CONCLUSION, FK_MUESTRA_ID, Moya_Diego
FROM INFORMES_FORENSES
WHERE ID = ?;